### ISSUE TITLE
Multiple activities emitted when using MongoDB Otel

### ISSUE THREAD

**Issue by rgmills** [jbogard/MongoDB.Driver.Core.Extensions.OpenTelemetry#1]
Hello! I've been kicking the tires on OTel and came across your library to do this.  I ran into a small issue when using in ASP.NET Core 3.1.    Here's a reproduction: https://github.com/rgmills/mongodb-otel-multipleactivities

Basically, when this listener is used, I'm seeing multiple Activities reported for the original web request. Here's a sample from Jaeger

![image](https://user-images.githubusercontent.com/178635/90965540-f54e5400-e496-11ea-9f00-983fca862809.png)

Let me know if there is anything else I can provide or if you think this should be opened against the main OTel project instead.

**Comment by jbogard** [comment]
I'm not sure where this is coming from tbqh, I can take a look.

**Comment by rgmills** [comment]
Yeah, it was a bit ambiguous to me. I did pull this repo down and reference the source (in our application code). Stepping through things *seemed* to happen in the order you'd expect but the handler didn't get the correct activity.

**Comment by rgmills** [comment]
Going to close this out. I've tried on a couple other exporters (zipkin and honeycomb) with 0.7.0-beta and I don't see duplicate issues like this.  Assuming this is just a Jaeger thing (which I won't be using anyway).
