### ISSUE TITLE
Support the released version of the OpenTelemetry 1.4.0

### ISSUE THREAD

**Issue by NickyNest** [jbogard/MongoDB.Driver.Core.Extensions.OpenTelemetry#10]
Please update to support the released version of the OpenTelemetry 1.4.0.

**Comment by mjkammer78** [comment]
Second this .. were getting conflicts in our applications on transitive dependencies since the currently linked OTEL requires **Microsoft.Extensions.Logging < 6.0.0** which would not be the default situation for current applications

**Comment by jbogard** [comment]
Ah, I meant to mark this package obsolete. There's no reason to use this package, it's a one-liner:

```csharp
﻿using System;

namespace OpenTelemetry.Trace
{
    public static class TracerProviderBuilderExtensions
    {
        public static TracerProviderBuilder AddMongoDBInstrumentation(this TracerProviderBuilder builder)
            => builder.AddSource("MongoDB.Driver.Core.Extensions.DiagnosticSources");
    }
}
```

It used to be more involved but now it's so simple to add sources, this package really doesn't have a reason to exist, other than causing transitive dependency problems.

**Comment by mjkammer78** [comment]
Ah great, guess we'll roll with that
