### ISSUE TITLE
Update to work with the latest OpenTelemetry 0.5.0-beta.2

### ISSUE THREAD

**Issue by dgrozenok** [jbogard/MongoDB.Driver.Core.Extensions.OpenTelemetry#2]
The instrumentation stopped working with the latest, probably breaking, changes in the OpenTelemetry. Even though activity is added in some cases, the kind, tags and command are not properly populated.

**Comment by jbogard** [comment]
Just pushed a new package with updated references.

**Comment by dgrozenok** [comment]
Thank you for such a quick turnaround!
