### ISSUE TITLE
Only sync functions are traced

### ISSUE THREAD

**Issue by dgrozenok** [jbogard/MongoDB.Driver.Core.Extensions.OpenTelemetry#3]
What am I doing wrong? I can only see the activities for the sync Mongo API calls. The Handlers of the DiagnosticsActivityEventSubscriber are called in all the cases both for sync and async function calls with CommandStartedEvent as well as the CommandSucceededEvent. However in the OpenTelemetry.Instrumentation.DiagnosticSourceListener.OnNext the Activity.Current is null for the async function call and is correct for the sync functions. I understood that the Activity.Current is supposed to be available in all threads.

**Comment by jbogard** [comment]
`Activity.Current` is only valid when the async context flows through correctly. That might not be true for the Mongo library. That's why I didn't try to use `Activity.Current` and instead would start it manually. I'm not familiar enough with the Mongo codebase to know for sure.

**Comment by dgrozenok** [comment]
Thank you for your response! I think you are right. The root cause is that Mongo driver may switch threads in asynchronous functions natively breaking the async flow. As a result while handling the completion of the command in MongoDB.Driver.Core.Extensions.DiagnosticSources you are trying to stop the activity from another thread, but the Activity.Current in null there. I submitted the pull request https://github.com/jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources/pull/1 that fixes the issue. With that all Mongo commands sync and async would be added to the trace. Here are some more details about such scenarios: https://github.com/dotnet/runtime/issues/25936.

**Comment by dgrozenok** [comment]
Just realized that fix only works in case the mongo command is the root activity, otherwise the Activity.Current is not null and the issue is still there. It's clear that the issue in the MongoDB.Driver.Core.Extensions.DiagnosticSources logic, so closing this issue and switching to that repository.
