### ISSUE TITLE
OTel RC1 is fubar

### ISSUE THREAD

**Issue by buvinghausen** [jbogard/MongoDB.Driver.Core.Extensions.OpenTelemetry#6]
https://github.com/open-telemetry/opentelemetry-dotnet/issues/1580

They went and made ActivitySourceAdapter, DiagnosticSourceSubscriber, & ListenerHandler all internal.  It broke not only this instrumentation provider but all the ones in their dotnet contrib project.   The best part was they didn't provide any guidance on how to work around the new accessibility level restrictions.

Not calling it out here because I want you to take action just calling it out to make sure there is awareness.

**Comment by jbogard** [comment]
Ruh roh.

**Comment by buvinghausen** [comment]
@jbogard I'm advocating they move DiagnosticSourceSubscriber & ListenerHandler to a separate package like OpenTelemetry.Instrumentation.Abstractions and restore the public accessiblity.

They have that thread going on for what to do about the ActivitySourceAdapter so I will let that run it's course.

First step is opening a PR on their end to allow .NET 5.0 to host the package in OpenTelemetry.Extensions.Hosting #babysteps

**Comment by buvinghausen** [comment]
Ahh they have moved the upper band up to v6 in the RC but then broke everything else LOL

**Comment by buvinghausen** [comment]
Over the holiday weekend I'm going to take a stab at reconciling the difference in how they did the StackExchange.Redis instrumentation (which doesn't use any of the internals) and both of your libraries.  I'll let you know what I find out but if I can log the appropriate activities into cloudwatch I'll open some PRs to discuss.

**Comment by jbogard** [comment]
I've pushed out a new package for this and the base library.
